# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'SampleProject' do
  pod 'SQUtils', :path => '..'

  # Pods for SampleProject

  target 'SampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
